# Семинар 1

## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки. 

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка" 
- `y` - изменить тип выбранной ячейки на "код" 
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [1]:
2 + 2

4

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [2]:
import numpy as np

In [3]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [6]:
vec.dtype

dtype('int32')

In [7]:
type(vec)

numpy.ndarray

Размер массива:

In [8]:
vec.shape

(3, 2)

Число осей:

In [9]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [10]:
np.sum(vec)

21

In [11]:
np.sum(vec, axis=0)

array([ 9, 12])

In [12]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [13]:
vec.sum()

21

Транспонируем массив:

In [14]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [16]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [17]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [20]:
vec[:, 1]

array([2, 4, 6])

In [21]:
vec[2, :]

array([5, 6])

In [22]:
vec[1:2, 0]

array([3])

In [23]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [24]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [25]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [26]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [27]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [28]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [29]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [30]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [31]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [32]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [33]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [35]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [36]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [37]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [38]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [39]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [40]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [ ]:
np.identity(5)

Массивы можно объединять:

In [41]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [43]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [44]:
np.random.rand(2, 3)

array([[0.7606557 , 0.98106625, 0.9044053 ],
       [0.01981081, 0.01663341, 0.61138503]])

In [45]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [46]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [47]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [48]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [49]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [50]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 19.9 s


In [51]:
%%time
C = A @ B

Wall time: 49.3 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [66]:
vec = np.random.randint(100, size=50)
vec

array([ 3, 88, 34, 23, 14, 91, 29, 52, 65, 12, 26, 43, 27, 50, 76, 18, 93,
       26, 13,  0, 78, 93, 34, 26, 55, 81, 68, 87, 92,  2, 78, 32, 10, 61,
       92, 67, 73,  3, 93, 20,  5, 80, 70, 75, 62,  9, 86, 17, 26, 16])

##### Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

In [67]:
%%time
vec[::-1]

Wall time: 0 ns


array([16, 26, 17, 86,  9, 62, 75, 70, 80,  5, 20, 93,  3, 73, 67, 92, 61,
       10, 32, 78,  2, 92, 87, 68, 81, 55, 26, 34, 93, 78,  0, 13, 26, 93,
       18, 76, 50, 27, 43, 26, 12, 65, 52, 29, 91, 14, 23, 34, 88,  3])

##### Найти максимальный нечетный элемент в массиве.

In [68]:
vec[vec % 2 == 1].max()

93

##### Замените все нечетные элементы массива на ваше любимое число.

In [70]:
vec[vec % 2 == 1] = 7
vec

array([ 7, 88, 34,  7, 14,  7,  7, 52,  7, 12, 26,  7,  7, 50, 76, 18,  7,
       26,  7,  0, 78,  7, 34, 26,  7,  7, 68,  7, 92,  2, 78, 32, 10,  7,
       92,  7,  7,  7,  7, 20,  7, 80, 70,  7, 62,  7, 86,  7, 26, 16])

##### Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [80]:
n = 6
data = np.arange(n * 2, 0, -1)
data[data % 2 == 1]

array([11,  9,  7,  5,  3,  1])

##### Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [83]:
number = 12.23
data = np.random.randint(100, size=(5, 5))
data

array([[12, 60, 12, 84, 72],
       [36, 35, 87,  0, 37],
       [ 8, 94, 55, 41, 71],
       [67,  8, 73, 24, 71],
       [80, 74, 48, 89, 12]])

In [95]:
diff = np.abs(data - number)
data.flatten()[np.argmax(diff)]

94

In [96]:
data.flatten()[diff.argmin()]

12

##### Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [121]:
data = np.array([8, 4, 7, 2, 5])
pw = np.arange(data.size)[::-1]
pw

array([4, 3, 2, 1, 0])

In [122]:
np.append(data / (pw + 1), np.random.randint(10))

array([1.6       , 1.        , 2.33333333, 1.        , 5.        ,
       8.        ])

##### Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [125]:
x = 2
deriv = (data * pw)[:-1]
deriv

array([32, 12, 14,  2])

In [126]:
(x ** (pw[:-1] - 1) * deriv).sum()

334